# Generated by Django 4.1.7 on 2023-04-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_customer_max_loan_customer_pending_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(default='', max_length=50)),
                ('customer_id', models.IntegerField(default=0)),
                ('product_id', models.IntegerField(default=0)),
                ('product_taken', models.IntegerField(default=0)),
                ('sub_cat', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='totalNumber',
            field=models.IntegerField(default=10),
        ),
    ]
