# Generated by Django 4.1.7 on 2023-04-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orderdetail_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='isReturn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='currentNumber',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='totalNumber',
            field=models.IntegerField(default=25),
        ),
    ]
