# Generated by Django 4.1.7 on 2023-04-02 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orderdetail_ispaid_orderdetail_isreturn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='currentNumber',
        ),
    ]
