# Generated by Django 4.1.7 on 2023-04-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_product_currentnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='totalNumber',
        ),
        migrations.AddField(
            model_name='product',
            name='currentNumber',
            field=models.IntegerField(default=25),
        ),
    ]
