# Generated by Django 4.1.7 on 2023-04-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pay',
            field=models.IntegerField(default=0),
        ),
    ]
