# Generated by Django 4.1.7 on 2023-04-03 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_payment_pay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='address',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='city',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='state',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='zip_code',
        ),
    ]
