# Generated by Django 4.1.7 on 2023-04-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_payment_address_remove_payment_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='year',
            field=models.IntegerField(default=''),
        ),
    ]
