# Generated by Django 4.1.7 on 2023-04-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='year',
            field=models.IntegerField(default=1),
        ),
    ]
